version: "3.9"  # optional since v1.27.0
services:
  mariadb:
    container_name: mariadb
    restart: unless-stopped
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wp:/var/www/html/wordpress
    expose:
      - "9000"
    networks:
      - inception
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - inception

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rchalmer/data/db
#      device: /home/oem/Desktop/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rchalmer/data/wp
#      device: /home/oem/Desktop/data/wp

networks:
  inception:
    driver: bridge