version: "3.9"  # optional since v1.27.0
services:
  mariadb:
    container_name: mariadb
    restart: unless-stopped
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}

    volumes:
      - db:/var/lib/mysql
    ports:
      - "5121:3306"
    networks:
      - inception
  wordpress:
    depends_on:
      - mariadb
#    env_file:
#      - .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
    container_name: wordpress
    restart: unless-stopped
    #    volumes:
    #      - wp:/var/www/html/wordpress
    volumes:
      - wp:/var/www/html/wordpress
    ports:
      - "8000:8000"
#    environment:
#      DB_HOST: ${DB_HOST}
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PASSWORD}
#      DB_NAME: ${DB_NAME}
    networks:
      - inception
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
#    volumes:
#      - wp:/var/www/html/wordpress
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - inception


volumes:
  db:
    name: db
    driver: local
#    external: true
    driver_opts:
      type: none
      o: bind
      device: /home/rchalmer/data/db
#      device: /home/oem/Desktop/data/db
  wp:
    name: wp
    driver: local
#    external: true
    driver_opts:
      type: none
      o: bind
      device: /home/rchalmer/data/wp
#      device: /home/oem/Desktop/data/wp

#volumes:
#  db: {}
#  wp: {}

networks:
  inception:
    driver: bridge