version: "3.9"  # optional since v1.27.0
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - .:/code
      - logvolume01:/var/log
    networks:
      - inception
    links:
      - redis
  redis:
    image: redis
volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USERNAME}/data/wp
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USERNAME}/data/wp